#include<stdio.h>
void main()
{
    int i,j,n;
    printf("Enter n:");
    scanf("%d",&n);
    for(i=1;i<=n;i++)
    {
        for(j=1;j<=i;j++)
        {
        printf("%d",j);
        }
        printf("\n");
    }
    for(i=1;i<=n;i++)
    {
        for(j=1;j<=i;j++)
        {
        printf("*",j);
        }
        printf("\n");
    }
    for(i=5;i>=1;i--)
    {
        for(j=5;j>=i;j--)
        {
        printf("%d",j);
        }
        printf("\n");
    }
    for(i=1;i<=n;i++)
    {
        for(j=1;j<=i;j++)
        {
            printf("*");
        }
        printf("\n");
    }
        for(i=5;i>=1;i--)
    {
        for(j=5;j>=i;j--)
        {
        printf("*");
        }
        printf("\n");
    }
    }